[tools]
node = "25"
pnpm = "10"
prettier = "3"

[tasks.format]
description = "Format code using Prettier"
run = "prettier --write ."

[tasks.check-format]
description = "Check code formatting using Prettier"
run = "prettier --check ."
